services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ShareButtonsBundle\Controller\:
        resource: '../../Controller/*'

    c975L\ShareButtonsBundle\Security\:
        resource: '../../Security/*'

    c975L\ShareButtonsBundle\Service\:
        resource: '../../Service/*'

    c975L\ShareButtonsBundle\Twig\:
        resource: '../../Twig/*'
