c975LShareButtons:
    roleNeeded:
        type: string
        required: true
        default: ROLE_ADMIN
        info: "User's role needed to enable access to data linked to ShareButtonsBundle: i.e. ROLE_ADMIN (default)"
