services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ShareButtonsBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\ShareButtonsBundle\Security\:
        resource: '../src/Security/*'

    c975L\ShareButtonsBundle\Service\:
        resource: '../src/Service/*'

    c975L\ShareButtonsBundle\Twig\:
        resource: '../src/Twig/*'
